### PR TITLE
Add OSGi support to marathon-client: OSGi metadata in MANIFEST.MF

### PR DESCRIPTION
**Pull request by bosschaert**

### CODE REVIEW

**Comment by bosschaert** [comment]
Ping any news on this? It would be great if someone could merge this pull request.

**Comment by colin-msphere** [comment]
Can you provide a summary of what this provides and how to use it? Does it alter the existing packaging?

**Comment by bosschaert** [comment]
Hi @colin-msphere, this allows this marathon-client to be used in an OSGi framework as well. OSGi is technology for Java Modularity that has [many implementations](https://en.wikipedia.org/wiki/OSGi_Specification_Implementations), such as Apache Felix and Eclipse Equinox. For more info on OSGi see https://en.wikipedia.org/wiki/OSGi or https://www.osgi.org/developer/architecture/ . 

This change adds extra metadata to the jar manifest which makes it usable as an OSGi bundle too. The extra headers are:
```
Bundle-Description: A Java API client for Mesosphere's Marathon.
Bundle-ManifestVersion: 2
Bundle-Name: marathon-client
Bundle-SymbolicName: com.mesosphere.marathon-client
Bundle-Version: 0.3.1.SNAPSHOT
Export-Package: mesosphere.marathon.client;uses:="feign,mesosphere.mar
 athon.client.model.v2,mesosphere.marathon.client.utils";version="0.3.
 1",mesosphere.marathon.client.auth;uses:=feign;version="0.3.1",mesosp
 here.marathon.client.model.v2;uses:="com.google.gson";version="0.3.1"
 ,mesosphere.marathon.client.utils;uses:="com.google.gson";version="0.
 3.1"
Import-Package: com.google.gson;version="[2.5,3)",com.google.gson.anno
 tations;version="[2.5,3)",feign;version="[8.14,9)",feign.auth;version
 ="[8.14,9)",feign.codec;version="[8.14,9)",feign.gson;version="[8.14,
 9)",mesosphere.marathon.client.auth,mesosphere.marathon.client.model.
 v2,mesosphere.marathon.client.utils
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.6))"

```

These headers don't affect users that are not running in an OSGi framework.

**Comment by kensipe** [comment]
LGTM

**Comment by kensipe** [comment]
@bosschaert thx!

**Pull request merged**
