### PR TITLE
Offer option to pass query parameters to /v2/apps

### PR DESCRIPTION
**Pull request by tegataiprime**
I found it useful to be able to use query parameters to filter the list of marathon applications.

### CODE REVIEW

**Comment by tegataiprime** [comment]
@colin-msphere Looking for review

**Comment by kensipe** [comment]
@tegataiprime our teammate has been out and I was previous to today unaware of that... I will take a look this week.  likely tomorrow.  sorry for the delay.

**Comment by tegataiprime** [comment]
@kensipe Thanks Ken.  I've got some changes to enable DCOS authentication ready for a [project](https://github.com/aatarasoff/spring-cloud-marathon) that depends on 0.3.1-SNAPSHOT of this project (currently what is in 'master').  It would be a great help if you would cut a 0.3.1 release after merging this PR.

**Comment by tegataiprime** [comment]
@kensipe Thanks for merging Ken.  What is your timeline for the next release?

**Pull request merged**
