### PR TITLE
Added missing state field

### PR DESCRIPTION
**Pull request by afraisse**

### CODE REVIEW

**Comment by afraisse** [comment]
Any update on this ?

**Comment by colin-msphere** [comment]
Can you link me to where the `state` field is defined for `Task`?

**Comment by afraisse** [comment]
Hi Colin,
Sadly it is not documented, but in Marathon's object model it is defined [here](https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/core/task/Task.scala#L64).

**Comment by colin-msphere** [comment]
Thank you.

**Comment by afraisse** [comment]
Any update on this one ?

**Comment by kensipe** [comment]
@afraisse I'm not sure what the issue was... could you fix the current conflict and I will review ASAP.

**Comment by kensipe** [comment]
@afraisse could you rebase?

**Comment by kensipe** [comment]
long PR time without response... closing.. please open or refile.   thanks for you involvement.

**Pull request closed without merging**
