### PR TITLE
Add AppWithVersion to handle version field in App

### PR DESCRIPTION
**Pull request by lewisheadden**
- Adds a new class called AppWithVersion which subclasses App and adds the `version` field to this object.
- Updates GetAppResponse and GetAppsResponse to use AppWithVersion
- Updates createApp to return AppWithVersion.
- Avoids problem of adding `version` to App which stops PUT requests working (can't PUT with `version` set on App)
- Standardize formatting in Marathon interface to use tabs as most other classes use and indent appropriately.

### CODE REVIEW

**Comment by kensipe** [comment]
@lewisheadden looks like it needs a rebase

**Comment by lewisheadden** [comment]
@kensipe rebased. Sorry this is a bit of a mess - trying to work out what style you guys are using. Do you have a formatter file?

**Comment by kensipe** [comment]
@lewisheadden can't apologize enough.  I'm not normally responsible for this repo... 
could you rebase 1 more time... I will look at it ASAP after.  thx!

**Comment by lewisheadden** [comment]
@kensipe apologies for the delay on getting back to you regarding this. I think I'm going to start afresh with a new PR against the latest version of your library.

**Pull request closed without merging**
